### ISSUE TITLE
Enripen

### ISSUE THREAD

**Issue by arjver** [denoland/deno-kv-hackathon#27]
## Team or Project Name
**Enripen** - A crowdsourced index to help against link rot.

## Team Members
Me (blobbybilb)

## Screenshots of your Project
<img width="200" alt="Screenshot 2023-06-15 at 11 36 24 AM" src="https://github.com/denoland/deno-kv-hackathon/assets/58201828/b5893be4-8a4c-4c59-861c-bf662e01b07c">

<img width="200" alt="Screenshot 2023-06-15 at 11 45 17 AM" src="https://github.com/denoland/deno-kv-hackathon/assets/58201828/35276ad7-5e0b-4279-b688-e418a974efad">

<img width="200" alt="Screenshot 2023-06-15 at 11 48 40 AM" src="https://github.com/denoland/deno-kv-hackathon/assets/58201828/88c31e38-2f1b-4f6e-a198-7c30c10a38a1">

## Link to demo on Deno Deploy
[Demo UI](https://enripen.deno.dev/) using Fresh
[API](https://enripen.deno.dev/api) using Hono embedded in a Fresh route
[API Doc](https://enripen.deno.dev/api/docs)

## Link to project's public GitHub repo
[Enripen - Github](https://github.com/blobbybilb/enripen)

## Any final comments you'd like to add?
The Demo UI is pretty basic because I was going to make a browser extension that uses the API but ran out of time 😅. I'll make the browser extension at some point...

Not sure what "All code must be created during the event" means exactly, but I did use some open source libraries (fresh, flowbite, and hono). If that disqualifies it then I have no problem :)

**Comment by lambtron** [comment]
you're good! thank you!
